### ISSUE TITLE
PHPParralelLint not installed

### ISSUE THREAD

**Issue by ChrisDBrown** [sspooky13/yaml-standards#17]
**Which version(s) is affected**: 4.0.0

**Description**
When installing as a dev dependency of another project `PHPParralelLint` is not included, as it is not defined in the composer file. Currently it's only included as it's a dependency of `shopsys/coding-standards`, so will only exist on dev installs.

**How to reproduce**
1) Create new project with `composer init`
2) `composer require --dev sspooky13/yaml-standards`
3) Attempt to scan a directory, for example `php vendor/bin/yaml-standards ./directory`

You'll get the following error:
`PHP Fatal error:  Uncaught Error: Class 'JakubOnderka\PhpParallelLint\RecursiveDirectoryFilterIterator' not found in {project folder}/vendor/sspooky13/yaml-standards/src/Service/YamlFilesPathService.php:28`

**Possible Solution**
Include this dependency in the composer file - will raise a PR for this shortly.

**Additional information**
Hope you don't mind me raising this - currently this is blocking me from using your tool on a personal project, so would be great to get this in. Do you mind me picking up some of the other issues on this repo if I've time after this is resolved?

**Comment by sspooky13** [comment]
Hello, thanks for your interest and PR. I accept your PR so I hope now install will be ok.

Sure, you can highlight, create or comment issues, every help is good.
Thanks
