### ISSUE TITLE
CI: build symfony 5 version

### ISSUE THREAD

**Issue by sspooky13** [sspooky13/yaml-standards#46]
**Which version(s) is affected**: ^5.0

**Description**
Symfony 5 can't be built because `shopsys/coding-standards` locked `symplify/easy-coding-standard` to `^5` version and this version locked `symfony` to version `^3.4|^4.1`
You can see in there https://travis-ci.org/sspooky13/yaml-standards/jobs/644890349

**Possible Solution**
1. copy from [easy-coding-standard.yml](https://github.com/shopsys/coding-standards/blob/master/easy-coding-standard.yml) to this project and upgrade `symplify/easy-coding-standard` but I will have to upgrade `easy-coding-standard.yml` manually
2. find other coding standards and use it but I am with `shopsys/coding-standards` yet satisfied 😐
3. create fork of `shopsys/coding-standards` and use it + create PR for upgrade

**Comment by vasilvestre** [comment]
Solution 3 in progress here https://github.com/shopsys/coding-standards/pull/14

**Comment by sspooky13** [comment]
fixed
