### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by sspooky13** [sspooky13/yaml-standards#56]
**Description**
Add support version PHP 8

**Alert**
First https://github.com/sspooky13/yaml-standards/issues/47 must be done

**Comment by herman-aka-wouter** [comment]
Any update on this?

**Comment by sspooky13** [comment]
hello @wouter-toppy,
honestly, I thought this library no one using so I devoted myself to other projects.
But if this library is used, I can try to resolve this.

**Comment by herman-aka-wouter** [comment]
I use this, a simple merge that php 8.0 is allowed will do for me ;-) I dont think there is more complecated things for it. if any issues occur, I'll let you know, and if neceserry, write a pull
