### ISSUE TITLE
glob() fails due GLOB_BRACE const usage, which is not available under alpine linux due non-standard libc (musl) usage

### ISSUE THREAD

**Issue by diimpp** [sspooky13/yaml-standards#76]
**Which version(s) is affected**: 8.0.0.

**Description**
> Warning: `Use of undefined constant GLOB_BRACE - assumed 'GLOB_BRACE'` (this will throw an Error in a future version of PHP) in /srv/sylius/vendor/sspooky13/yaml-standards/src/Command/Service/FilesPathService.php on line 38
> Fatal error: Uncaught TypeError: `glob() expects parameter 2 to be int, string given` in /srv/sylius/vendor/sspooky13/yaml-standards/src/Command/Service/FilesPathService.php:38

<details><summary>Full log</summary>
<p>

```log
Warning: Use of undefined constant GLOB_BRACE - assumed 'GLOB_BRACE' (this will throw an Error in a future version of PHP) in /srv/sylius/vendor/sspooky13/yaml-standards/src/Command/Service/FilesPathService.php on line 38

Fatal error: Uncaught TypeError: glob() expects parameter 2 to be int, string given in /srv/sylius/vendor/sspooky13/yaml-standards/src/Command/Service/FilesPathService.php:38
Stack trace:
#0 /srv/sylius/vendor/sspooky13/yaml-standards/src/Command/Service/FilesPathService.php(38): glob('./*{.yml,.yaml,...', 'GLOB_BRACE')
#1 /srv/sylius/vendor/sspooky13/yaml-standards/src/Command/Service/FilesPathService.php(20): YamlStandards\Command\Service\FilesPathService::globRecursive('./*{.yml,.yaml,...')
#2 /srv/sylius/vendor/sspooky13/yaml-standards/src/Model/Config/YamlStandardConfigLoader.php(43): YamlStandards\Command\Service\FilesPathService::getPathToFiles(Array)
#3 /srv/sylius/vendor/sspooky13/yaml-standards/src/Model/Config/YamlStandardConfigLoader.php(31): YamlStandards\Model\Config\YamlStandardConfigLoader->createConfigData(Array)
#4 /srv/sylius/vendor/sspooky13/yaml-standards/src/Command/YamlCommand.php(51): YamlStandards\Model\Config\YamlStandardConfigLoader->loadFromYaml('./yaml-standard...')
#5 /srv/sylius/vendor/symfo in /srv/sylius/vendor/sspooky13/yaml-standards/src/Command/Service/FilesPathService.php on line 38
```

</p>
</details>

**How to reproduce**
call yaml-standard bin from docker with alpine linux

**Possible Solution**

Handle possiblity of  `GLOB_BRACE` missing.

https://www.php.net/manual/en/function.glob.php

![image](https://github.com/sspooky13/yaml-standards/assets/870747/e226e38c-60a9-4dfe-90f9-53ae9373f295)

**Additional information**
https://github.com/zendframework/zend-stdlib/issues/58
zend-stdlib has fallback glob for this exact issue https://github.com/zendframework/zend-stdlib/blob/6d965efcce81ee60e2b425792f1cd3f27aed82d9/src/Glob.php#L39-L46

**Comment by sspooky13** [comment]
Hello, thanks for report. I will work on it.

**Comment by sspooky13** [comment]
@diimpp, I fixed this issue like [Symfony](https://github.com/symfony/finder/commit/a0c9d353abe5698ef2cba586b1e1601fc211cb75) and some more repositories -> https://github.com/sspooky13/yaml-standards/commit/48d206f3cda4d5a9d16e1322f34399113eb920e7. Is it OK for you or do you really want to use GLOB_BRACE constant?

Thanks

**Comment by diimpp** [comment]
Just patched my local version with it and seems to work correctly.

- `vendor/bin/yaml-standards` is being called without errors now
- Number of found files matches number of files in directory with ` find path/to/dir -mindepth 1 -type f -name "*.yml" -printf x | wc -c` for yml/yaml file extensions.

Thank you for super fast fix :)

EDIT: P.S. Yes, it's okay for me and I've no use for GLOB_BRACE const directly.

**Comment by sspooky13** [comment]
You are welcome 😊 I released new version where is this issue fixed, so you can change version in `composer.json` to don't have to change your localhost version

Thank you for your report
