### ISSUE TITLE
YamlIndentChecker - PHP error on Differ creation

### ISSUE THREAD

**Issue by p-golovin** [sspooky13/yaml-standards#83]
**Which version(s) is affected**: 8.1.0

**Description**
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function SebastianBergmann\Diff\Differ::__construct(), 0 passed in vendor/sspooky13/yaml-standards/src/Model/YamlIndent/YamlIndentChecker.php on line 38 and exactly 1 expected in vendor/sebastian/diff/src/Differ.php:40

**Additional information**
sebastian/diff                        5.1.1

**Comment by sspooky13** [comment]
Hello, it's fixed in master branch but I don't have time to finish necessary PR for next release, so I will extract fixes from master and raise new version. In couple of ~~hours~~ minutes, it will be done. Thanks

**Comment by sspooky13** [comment]
fixed in version 8.1.1
